sdk: "/Users/idrissadiatta/.rvm/gems/ruby-1.9.2-p180/gems/rhodes-3.0.1"
sdkversion: 3.0.1
name: allosante
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
android:
    minSDK: 8
iphone:
  configuration: Debug
  sdk: iphonesimulator4.3
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.allosante
  BundleURLScheme: allosante
wp:
  productid: 'bdc777b0-770d-012e-0f04-58b035efe91f'

extensions: ["json", "another-extension"]
